# Generated by Django 4.1.3 on 2022-11-20 17:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnails', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('original_file_available', models.BooleanField()),
                ('binary_file_available', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise'), ("{('BASIC', 'Basic'): [200], ('PREMIUM', 'Premium'): [200, 400], ('ENTERPRISE', 'Enterprise'): [0, 200, 400]}", ' Tierlist  Mapped Thumb Sizes')], default='BASIC', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tier'),
        ),
    ]
