# Generated by Django 4.1.3 on 2022-11-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_tier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tier',
            old_name='binary_file_available',
            new_name='binary_file_access',
        ),
        migrations.RenameField(
            model_name='tier',
            old_name='original_file_available',
            new_name='original_file_access',
        ),
        migrations.RenameField(
            model_name='tier',
            old_name='thumbnails',
            new_name='thumbnail_sizes',
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('CUSTOM', 'Custom'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=255),
        ),
    ]
