# Generated by Django 4.1.3 on 2022-11-16 18:32

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='images/default.jpg', upload_to=images.models.upload_to)),
                ('description', models.CharField(max_length=40)),
            ],
        ),
    ]
