# Generated by Django 4.1.3 on 2022-11-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_file_50'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_50',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
