# Generated by Django 4.1.3 on 2022-11-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_remove_image_description_image_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(default='elo', max_length=40),
            preserve_default=False,
        ),
    ]
