# Generated by Django 4.1.3 on 2022-11-17 22:22

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_remove_image_file_50_image_file_200px_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to=images.models.upload_to)),
            ],
        ),
    ]
