# Generated by Django 4.1.3 on 2022-11-18 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_binaryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BinaryImage',
        ),
        migrations.AddField(
            model_name='image',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
