# Generated by Django 4.1.3 on 2022-11-20 20:14

from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_delete_binaryimage_image_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=images.models.upload_to)),
                ('filepath', models.CharField(max_length=50)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='images.image')),
            ],
        ),
    ]
