# Generated by Django 4.1.3 on 2022-11-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_remove_image_file_200px_remove_image_file_400px'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='filepath',
            field=models.CharField(max_length=100),
        ),
    ]
