# Generated by Django 4.1.3 on 2022-11-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_alter_thumbnail_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='filepath',
            field=models.CharField(max_length=160),
        ),
    ]
