# Generated by Django 4.1.3 on 2022-11-21 01:09

from django.db import migrations, models
import images.models
import images.validators


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_alter_thumbnail_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=images.models.upload_to, validators=[images.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='file',
            field=models.ImageField(upload_to='.', validators=[images.validators.validate_image_extension]),
        ),
    ]
